name: Build Binaries

on:
  pull_request:
    branches:
      - '*'

env:
  GO_VERSION: '1.21'
  CGO_ENABLED: 0
  IN_DOCKER: ""

jobs:

  build-webui:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build webui
        run: |
          make clean-webui generate-webui
          # Workaround for tar trying to archive the output archive. Must be excluded as well.
          touch traefik.src.tar.gz
          tar czvf traefik.src.tar.gz \
            --exclude traefik.src.tar.gz \
            --exclude-vcs \
            --exclude .github \
            .

      - name: Artifact webui
        uses: actions/upload-artifact@v2
        with:
          name: traefik.src.tar.gz
          path: traefik.src.tar.gz
