name: Build Binaries

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'script/gcg/**'

env:
  GO_VERSION: '1.23'
  CGO_ENABLED: 0

jobs:

  build-webui:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: webui/.nvmrc
          cache: yarn
          cache-dependency-path: webui/yarn.lock

      - name: Build webui
        working-directory: ./webui
        run: |
          yarn install
          yarn build

      - name: Package webui
        run: |
          # Workaround for tar trying to archive the output archive. Must be excluded as well.
          touch traefik.src.tar.gz
          tar czvf traefik.src.tar.gz \
            --exclude traefik.src.tar.gz \
            --exclude-vcs \
            --exclude .github \
            .

      - name: Artifact webui
        uses: actions/upload-artifact@v4
        with:
          name: traefik.src.tar.gz
          path: traefik.src.tar.gz
